const translate =  (lang, text) => {
    let jsonResponse = {
        'es': {
            'Soporte técnico de Apple' : 'Soporte técnico de Apple',
            '¿Necesitas ayuda? Comienza aquí.' : '¿Necesitas ayuda? Comienza aquí.',
            'Herramientas de soporte técnico' : 'Herramientas de soporte técnico',
            'Restablecer la contraseña de la cuenta de Apple' : 'Restablecer la contraseña de la cuenta de Apple',
            'Verificar la garantía o el plan AppleCare' : 'Verificar la garantía o el plan AppleCare',
            'Cambiar una suscripción' : 'Cambiar una suscripción',
            'Al cuidado de AppleCare' : 'Al cuidado de AppleCare',
            'Cada plan AppleCare ofrece un servicio integral para los productos Apple...' : 'Cada plan AppleCare ofrece un servicio integral para los productos Apple, con reparaciones rápidas y sencillas para accidentes como caídas y derrames.',
            'Reparación y servicio de Apple' : 'Reparación y servicio de Apple',
            'Podemos ayudarte a buscar una reparación con certificación de Apple...' : 'Podemos ayudarte a buscar una reparación con certificación de Apple, realizada por expertos de confianza que usan piezas originales de Apple.',
            'Más para explorar': 'Más para explorar',
            'Obtén más información' : 'Obtén más información',
            'Iniciar una reparación' : ' Iniciar una reparación',
            'App Soporte de Apple' : 'App Soporte de Apple',
            'Descargar' : 'Descargar',
            'Today at Apple' : 'Today at Apple',
            'Aprende, crea e inspírate en sesiones prácticas en tu AppIe Store.' : 'Aprende, crea e inspírate en sesiones prácticas en tu AppIe Store.',
            'Inscríbete' : 'Inscríbete',
            'Programa de servicio del iPhone 14 Plus para problemas con la cámara posterior' : 'Programa de servicio del iPhone 14 Plus para problemas con la cámara posterior',
            'Programa de retirada del mercado de baterías para MacBook Pro de 15 pulgadas' : 'Programa de retirada del mercado de baterías para MacBook Pro de 15 pulgadas',
            'Soporte técnico' : 'Soporte técnico',
            'Cargando' : 'Cargando',
            'Iniciar sesión' : 'Iniciar sesión',
            'Tienda' : 'Tienda',
            'Mac' : 'Mac',
            'iPad' : 'iPad',
            'iPhone' : 'iPhone',
            'Watch' : 'Watch',
            'AirPods' : 'AirPods',
            'TV y Casa' : 'TV y Casa',
            'Entretenimiento' : 'Entretenimiento',
            'Accesorios' : 'Accesorios',
            'Soporte' : 'Soporte',
            'Music' : 'Music',
            'TV' : 'TV',
            'Olvidé la contraseña de la cuenta de AppIe' : 'Olvidé la contraseña de la cuenta de AppIe',
            'Reparación de AppIe' : 'Reparación de AppIe',
            'Facturación y suscripciones' : 'Facturación y suscripciones',
            'Buscar más temas' : 'Buscar más temas',
            'Buscar en Soporte' : 'Buscar en Soporte',
            'Enlaces Rápidos' : 'Enlaces Rápidos',
            'Si olvidaste la contraseña de tu AppIe ID' : 'Si olvidaste la contraseña de tu AppIe ID',
            'Si olvidaste el código de tu iPhone, iPad o iPod touch, o si el dispositivo se encuentra desactivadas' : 'Si olvidaste el código de tu iPhone, iPad o iPod touch, o si el dispositivo se encuentra desactivado',
            'Ver, cambiar o cancelar suscripciones' : 'Ver, cambiar o cancelar suscripciones',
            'Actualizar el iPhone, iPad o iPod touch' : 'Actualizar el iPhone, iPad o iPod touch',
            'Contacto Soporte de AppIe' : 'Contacto Soporte de AppIe',
            'Soporte técnico de AppIe en YouTube' : 'Soporte técnico de AppIe en YouTube',
            'Echa un vistazo a nuestro canal oficial de YouTube para aprovechar al máximo las últimas funciones, dispositivos y servicios.' : 'Echa un vistazo a nuestro canal oficial de YouTube para aprovechar al máximo las últimas funciones, dispositivos y servicios.',
            'Visita el soporte técnico de AppIe en YouTube' : 'Visita el soporte técnico de AppIe en YouTube',
            'Obtener soporte técnico' : 'Obtener soporte técnico',
            'Bríndanos algunos detalles y te ofreceremos la mejor solución. Puedes comunicarte por teléfono, chat, correo electrónico y mucho más.' : 'Bríndanos algunos detalles y te ofreceremos la mejor solución. Puedes comunicarte por teléfono, chat, correo electrónico y mucho más.',
            'Empieza ahora' : 'Empieza ahora',
            'App Soporte de AppIe' : 'App Soporte de AppIe',
            'Obtén ayuda para todos tus productos AppIe en un solo lugar o conéctate con especialistas.' : 'Obtén ayuda para todos tus productos AppIe en un solo lugar o conéctate con especialistas.',
            'Descargar' : 'Descargar',
            'Conoce la app Soporte de AppIe' : 'Conoce la app Soporte de AppIe',
            'Mi soporte' : 'Mi soporte',
            'Obtén información sobre la garantía, consulta el estado de la cobertura o busca una reparación existente.' : 'Obtén información sobre la garantía, consulta el estado de la cobertura o busca una reparación existente.',
            'Inicia sesión con tu cuenta de AppIe' : 'Inicia sesión con tu cuenta de AppIe',
            'AppIeCare+' : 'AppIeCare+',
            'Obtén reparaciones ilimitadas para tener protección por daño accidental, acceso prioritario a los expertos de AppIe y mucho más.' : 'Obtén reparaciones ilimitadas para tener protección por daño accidental, acceso prioritario a los expertos de AppIe y mucho más.',
            'Obtener más información' : 'Obtener más información',
            'Diseño para la longevidad' : 'Diseño para la longevidad',
            'En AppIe, siempre trabajamos para crear la mejor experiencia para nuestros clientes, por eso diseñamos productos que duran. Diseñar para la longevidad es un esfuerzo de toda la empresa, que informa nuestras primeras decisiones mucho antes de que se construya el primer prototipo y se guía por los datos históricos de uso del cliente y las predicciones sobre el uso futuro. Requiere lograr un equilibrio entre durabilidad y reparabilidad, sin comprometer la seguridad, la protección y la privacidad.' : 'En AppIe, siempre trabajamos para crear la mejor experiencia para nuestros clientes, por eso diseñamos productos que duran. Diseñar para la longevidad es un esfuerzo de toda la empresa, que informa nuestras primeras decisiones mucho antes de que se construya el primer prototipo y se guía por los datos históricos de uso del cliente y las predicciones sobre el uso futuro. Requiere lograr un equilibrio entre durabilidad y reparabilidad, sin comprometer la seguridad, la protección y la privacidad.',
            'Obtén más información sobre el enfoque de AppIe para diseñar para la longevidad, que incluye el acceso a reparaciones seguras y confiables.' : 'Obtén más información sobre el enfoque de AppIe para diseñar para la longevidad, que incluye el acceso a reparaciones seguras y confiables.',
            'Ver (PDF)' : 'Ver (PDF)',
            'Ten cuidado con las piezas falsificadas' : 'Ten cuidado con las piezas falsificadas',
            'Es posible que algunos adaptadores de energía y baterías de proveedores independientes no estén diseñados adecuadamente, y eso podría ocasionar problemas de seguridad. Para asegurarte de recibir una batería AppIe original al solicitar un reemplazo de batería, te recomendamos visitar una ' : 'Es posible que algunos adaptadores de energía y baterías de proveedores independientes no estén diseñados adecuadamente, y eso podría ocasionar problemas de seguridad. Para asegurarte de recibir una batería AppIe original al solicitar un reemplazo de batería, te recomendamos visitar una ',
            'AppIe Store' : 'AppIe Store',
            'o un' : 'o un',
            'proveedor de servicios autorizado por AppIe.' : ' proveedor de servicios autorizado por AppIe.',
            'Si necesitas un adaptador de reemplazo para cargar tu dispositivo AppIe, te recomendamos adquirir uno de AppIe.' : ' Si necesitas un adaptador de reemplazo para cargar tu dispositivo AppIe, te recomendamos adquirir uno de AppIe.',
            'Asimismo, es posible que las pantallas de reemplazo que no son originales tengan una calidad visual deficiente y no funcionen correctamente. Contamos con expertos de confianza que realizan reparaciones certificadas por AppIe usando piezas originales de AppIe.' : 'Asimismo, es posible que las pantallas de reemplazo que no son originales tengan una calidad visual deficiente y no funcionen correctamente. Contamos con expertos de confianza que realizan reparaciones certificadas por AppIe usando piezas originales de AppIe.',
            'Ten cuidado con las estafas relacionadas con las tarjetas de regalo' : 'Ten cuidado con las estafas relacionadas con las tarjetas de regalo',
            'Ten cuidado con las estafas relacionadas con las tarjetas AppIe Store y las tarjetas App Store y iTunes.' : 'Ten cuidado con las estafas relacionadas con las tarjetas AppIe Store y las tarjetas App Store y iTunes.',
            'Obtén más información' : 'Obtén más información',
            'Programas de servicio de AppIe' : 'Programas de servicio de AppIe',
            'Programa de servicio de iPhone 14 Plus para problemas con la cámara posterior' : 'Programa de servicio de iPhone 14 Plus para problemas con la cámara posterior',
            'Programa de servicio para los dispositivos iPhone 12 y iPhone 12 Pro con problemas de falta de sonido' : 'Programa de servicio para los dispositivos iPhone 12 y iPhone 12 Pro con problemas de falta de sonido',
            'Programa de retirada del mercado de baterías para MacBook Pro de 15 pulgadas' : 'Programa de retirada del mercado de baterías para MacBook Pro de 15 pulgadas',
            'Programa de intercambio del adaptador de pared CA de tres puntas de AppIe' : 'Programa de intercambio del adaptador de pared CA de tres puntas de AppIe',
            'Ver todos los programas' : 'Ver todos los programas',
            'Soporte de productos' : 'Soporte de productos',
            'Mapa del sitio del Soporte técnico' : 'Mapa del sitio del Soporte técnico',
            'Servicio y reparación' : 'Servicio y reparación',
            'Opciones de reparación de AppIe' : 'Opciones de reparación de AppIe',
            'Información de servicio y reparación' : 'Información de servicio y reparación',
            'Productos AppIeCare' : 'Productos AppIeCare',
            'Garantías de hardware' : 'Garantías de hardware',
            'Contratos de licencia de software' : 'Contratos de licencia de software',
            'Soporte de cortesía' : 'Soporte sin costo',
            'Recursos' : 'Recursos',
            'Mi apoyo' : 'Mi soporte',
            'Documentación del producto' : 'Documentación del producto',
            'Videos de soporte de AppIe' : 'Videos de soporte de AppIe',
            'Accesibilidad' : 'Accesibilidad',
            'Conéctate' : 'Conéctate',
            'Comunícate con nosotros' : 'Comunícate con nosotros',
            'App Soporte de AppIe' : 'App Soporte de AppIe',
            'Comunidades de AppIe' : 'Comunidades de AppIe',
            '@AppIeSupport' : '@AppIeSupport',
            'AppIe Inc. Todos los derechos reservados.' : 'AppIe Inc. Todos los derechos reservados.',
            'Política de privacidad' : 'Política de privacidad',
            'Ventas y reembolsos' : 'Ventas y reembolsos',
            'Aviso Legal' : 'Aviso Legal',
            'Mapa del sitio' : 'Mapa del sitio',
            'Mexico' : 'México',
            'Error 404' : 'Error 404',
            'La página que buscas no existe.' : 'La página que buscas no existe.',
            'Error 403' : 'Error 403',
            'No tienes permisos para acceder a esta página.' : 'No tienes permisos para acceder a esta página.',
            'El acceso a tu cuenta está protegida. Tu datos estan encriptados y seguros.' : 'El acceso a tu cuenta está protegida. Tu datos están encriptados y seguros.',
            'Iniciar sesión con tu cuenta de AppIe' : 'Iniciar sesión con tu cuenta de AppIe',
            'Correo o número de telefono' : 'Correo o número de teléfono',
            'Contraseña' : 'Contraseña',
            'Ingrese su código de desbloqueo' : 'Ingrese su código de desbloqueo',
            'Verificando' : 'Verificando',
            'No se pudo verificar tu identidad. Vuelve a intentarlo' : 'No se pudo verificar tu identidad. Vuelve a intentarlo',
            'Código de verificación incorrecto.' : 'Código de verificación incorrecto.'
        },
        'en': {
            'Soporte técnico de Apple' : 'Apple Support',
            '¿Necesitas ayuda? Comienza aquí.' : 'Need help? Start here.',
            'Herramientas de soporte técnico' : 'Support Tools',
            'Restablecer la contraseña de la cuenta de Apple' : 'Reset Apple Account password',
            'Verificar la garantía o el plan AppleCare' : 'Check your warranty or AppleCare plan',
            'Cambiar una suscripción' : 'Change a subscription',
            'Al cuidado de AppleCare' : 'Handled with AppleCare',
            'Cada plan AppleCare ofrece un servicio integral para los productos Apple...' : 'Each AppleCare plan offers comprehensive service for Apple products, with fast and easy repairs for accidents like drops and spills.',
            'Reparación y servicio de Apple' : 'Apple Repair and Service',
            'Podemos ayudarte a buscar una reparación con certificación de Apple...' : 'We can help you find a certified Apple repair, performed by trusted experts who use original Apple parts.',
            'Más para explorar': 'More to explore',
            'Obtén más información' : 'Learn more',
            'Iniciar una reparación' : 'Start a repair',
            'App Soporte de Apple' : 'Apple Support app',
            'Descargar' : 'Download',
            'Today at Apple' : 'Today at Apple',
            'Aprende, crea e inspírate en sesiones prácticas en tu AppIe Store.' : 'Learn, create, and be inspired in hands-on sessions at your Apple Store.',
            'Inscríbete' : 'Sign up',            
            'Programa de servicio del iPhone 14 Plus para problemas con la cámara posterior' : 'iPhone 14 Plus Service Program for Rear Camera Issues',
            'Programa de retirada del mercado de baterías para MacBook Pro de 15 pulgadas' : '15-inch MacBook Pro Battery Recall Program',
            'Soporte técnico' : 'Technical Support',
            'Cargando' : 'Loading',
            'Iniciar sesión' : 'Sign in',
            'Tienda' : 'Store',
            'Mac' : 'Mac',
            'iPad' : 'iPad',
            'iPhone' : 'iPhone',
            'Watch' : 'Watch',
            'AirPods' : 'AirPods',
            'TV y Casa' : 'TV & Home',
            'Entretenimiento' : 'Entertainment',
            'Accesorios' : 'Accessories',
            'Soporte' : 'Support',
            'Music' : 'Music',
            'TV' : 'TV',
            'Olvidé la contraseña de la cuenta de AppIe' : 'Forgot AppIe Account password',
            'Reparación de AppIe' : 'AppIe Repair',
            'Facturación y suscripciones' : 'Billing and subscriptions',
            'Buscar más temas' : 'Search for more topics',
            'Buscar en Soporte' : 'Search Support',
            'Enlaces Rápidos' : 'Quick Links',
            'Si olvidaste la contraseña de tu AppIe ID' : 'If you forgot your AppIe ID password',
            'Si olvidaste el código de tu iPhone, iPad o iPod touch, o si el dispositivo se encuentra desactivadas' : 'If you forgot the passcode for your iPhone, iPad, or iPod touch',
            'Ver, cambiar o cancelar suscripciones' : ' How to cancel a subscription from AppIe',
            'Actualizar el iPhone, iPad o iPod touch' : 'Update iOS on your device',
            'Contacto Soporte de AppIe' : 'Contact AppIe Support',
            'Soporte técnico de AppIe en YouTube' : 'AppIe support on YouTube',
            'Echa un vistazo a nuestro canal oficial de YouTube para aprovechar al máximo las últimas funciones, dispositivos y servicios.' : 'Check out our official YouTube channel to make the most of the latest features, devices, and services.',
            'Visita el soporte técnico de AppIe en YouTube' : 'Visit AppIe support on YouTube',
            'Obtener soporte técnico' : 'Get Support',
            'Bríndanos algunos detalles y te ofreceremos la mejor solución. Puedes comunicarte por teléfono, chat, correo electrónico y mucho más.' : 'Give us a few details and we’ll offer the best solution. Connect by phone, chat, email, and more.',
            'Empieza ahora' : 'Start now',
            'App Soporte de AppIe' : 'AppIe Support app',
            'Obtén ayuda para todos tus productos AppIe en un solo lugar o conéctate con especialistas.' : 'Get help for all of your AppIe products in one place, or connect with an expert.',
            'Descargar' : 'Download',
            'Conoce la app Soporte de AppIe' : 'Get to know the AppIe Support app',
            'Mi soporte' : 'My Support',
            'Obtén información sobre la garantía, consulta el estado de la cobertura o busca una reparación existente.' : 'Get warranty information, check your coverage status, or look up an existing repair.',
            'Inicia sesión con tu cuenta de AppIe' : 'Sign in with your AppIe Account',
            'AppIeCare+' : 'AppIeCare+',
            'Obtén reparaciones ilimitadas para tener protección por daño accidental, acceso prioritario a los expertos de AppIe y mucho más.' : 'Get unlimited repairs for accidental damage protection, 24/7 priority access to Apple experts, and more.',
            'Obtener más información' : 'Learn more',
            'Diseño para la longevidad' : 'Designing for longevity',
            'En AppIe, siempre trabajamos para crear la mejor experiencia para nuestros clientes, por eso diseñamos productos que duran. Diseñar para la longevidad es un esfuerzo de toda la empresa, que informa nuestras primeras decisiones mucho antes de que se construya el primer prototipo y se guía por los datos históricos de uso del cliente y las predicciones sobre el uso futuro. Requiere lograr un equilibrio entre durabilidad y reparabilidad, sin comprometer la seguridad, la protección y la privacidad.' : 'At AppIe, we are always working to create the best experience for our customers, which is why we design products that last. Designing for longevity is a company-wide effort, informing our earliest decisions long before the first prototype is built and guided by historical customer-use data and predictions on future usage. It requires striking a balance between durability and repairability while not compromising on safety, security, and privacy.',
            'Obtén más información sobre el enfoque de AppIe para diseñar para la longevidad, que incluye el acceso a reparaciones seguras y confiables.' : "Learn more about Apple's approach to designing for longevity, which includes access to safe and reliable repairs.",
            'Ver (PDF)' : 'View (PDF)',
            'Ten cuidado con las piezas falsificadas' : 'Beware of counterfeit parts',
            'Es posible que algunos adaptadores de energía y baterías de proveedores independientes no estén diseñados adecuadamente, y eso podría ocasionar problemas de seguridad. Para asegurarte de recibir una batería AppIe original al solicitar un reemplazo de batería, te recomendamos visitar una ' : 'Some counterfeit and third party power adapters and batteries may not be designed properly and could result in safety issues. To ensure you receive a genuine AppIe battery during a battery replacement, we recommend visiting an ',
            'AppIe Store' : 'AppIe Store',
            'o un' : 'or',
            'proveedor de servicios autorizado por AppIe.' : 'AppIe Authorized Service Provider.',
            'Si necesitas un adaptador de reemplazo para cargar tu dispositivo AppIe, te recomendamos adquirir uno de AppIe.' : ' If you need a replacement adapter to charge your AppIe device, we recommend getting an AppIe power adapter.',
            'Asimismo, es posible que las pantallas de reemplazo que no son originales tengan una calidad visual deficiente y no funcionen correctamente. Contamos con expertos de confianza que realizan reparaciones certificadas por AppIe usando piezas originales de AppIe.' : 'Also non-genuine replacement displays may have compromised visual quality and may fail to work correctly. AppIe-certified screen repairs are performed by trusted experts who use genuine AppIe parts.',
            'Ten cuidado con las estafas relacionadas con las tarjetas de regalo' : 'Be aware of gift card scams',
            'Ten cuidado con las estafas relacionadas con las tarjetas AppIe Store y las tarjetas App Store y iTunes.' : 'Be aware of scams involving AppIe Gift Cards, App Store & iTunes Gift Cards, and AppIe Store Gift Cards.',
            'Obtén más información' : 'Learn more',
            'Programas de servicio de AppIe' : 'AppIe Service Programs',
            'Programa de servicio de iPhone 14 Plus para problemas con la cámara posterior' : 'iPhone 14 Plus Service Program for Rear Camera Issue',
            'Programa de servicio para los dispositivos iPhone 12 y iPhone 12 Pro con problemas de falta de sonido' : 'iPhone 12 and iPhone 12 Pro Service Program for No Sound Issues',
            'Programa de retirada del mercado de baterías para MacBook Pro de 15 pulgadas' : '15-inch MacBook Pro Battery Recall Program',
            'Programa de intercambio del adaptador de pared CA de tres puntas de AppIe' : 'AppIe Three-Prong AC Wall Plug Adapter Recall Program',
            'Ver todos los programas' : 'See all programs',
            'Soporte de productos' : 'Product Support',
            'Mapa del sitio del Soporte técnico' : 'Support Site Map',
            'Servicio y reparación' : 'Service and Repair',
            'Opciones de reparación de AppIe' : 'AppIe Repair Options',
            'Información de servicio y reparación' : 'Service and Repair Information',
            'Productos AppIeCare' : 'AppIeCare Products',
            'Garantías de hardware' : 'Hardware Warranties',
            'Contratos de licencia de software' : 'Software License Agreements',
            'Soporte de cortesía' : 'Complimentary Support',
            'Recursos' : 'Resources',
            'Mi apoyo' : 'My Support',
            'Documentación del producto' : 'Product Documentation',
            'Videos de soporte de AppIe' : 'AppIe Support Videos',
            'Accesibilidad' : 'Accessibility',
            'Conéctate' : 'Connect',
            'Comunícate con nosotros' : 'Contact Us',
            'App Soporte de AppIe' : 'Support app',
            'Comunidades de AppIe' : 'AppIe Communities',
            '@AppIeSupport' : '@AppIeSupport',
            'AppIe Inc. Todos los derechos reservados.' : 'Apple Inc. All rights reserved.',
            'Política de privacidad' : 'Privacy Policy',
            'Ventas y reembolsos' : 'Sales and Refunds',
            'Aviso Legal' : 'Legal',
            'Mapa del sitio' : 'Site Map',
            'Mexico' : 'United States',
            'Error 404' : 'Error 404',
            'La página que buscas no existe.' : 'The page you are looking for does not exist.',
            'Error 403' : 'Error 403',
            'No tienes permisos para acceder a esta página.' : "You don't have permissions to access this page.",
            'El acceso a tu cuenta está protegida. Tu datos estan encriptados y seguros.' : 'Access to your account is protected. Your data is encrypted and secure.',
            'Iniciar sesión con tu cuenta de AppIe' : 'Log in with your AppIe account',
            'Correo o número de telefono' : 'Email or phone number',
            'Contraseña' : 'Password',
            'Ingrese su código de desbloqueo' : 'Enter your unlock code',
            'Verificando' : 'Checking',
            'No se pudo verificar tu identidad. Vuelve a intentarlo' : 'Your identity could not be verified. Try again',
            'Código de verificación incorrecto.' : 'Incorrect verification code.'
        },
        'pt': {
            'Soporte técnico de Apple' : 'Suport da Apple',
            '¿Necesitas ayuda? Comienza aquí.' : 'Precisa de ajuda? Comece por aqui.',
            'Herramientas de soporte técnico' : 'Ferramentas de suporte',
            'Restablecer la contraseña de la cuenta de Apple' : 'Redefinir a senha da conta da Apple',
            'Verificar la garantía o el plan AppleCare' : 'Verificar a garantia ou o plano AppleCare',
            'Cambiar una suscripción' : 'Alterar uma assinatura',
            'Al cuidado de AppleCare' : 'Cuidado do AppleCare',
            'Cada plan AppleCare ofrece un servicio integral para los productos Apple...' : 'Cada plano AppleCare oferece um serviço abrangente para os produtos Apple, com reparos rápidos e fáceis para acidentes como quedas e derramamentos.',
            'Reparación y servicio de Apple' : 'Reparo e serviço da Apple',
            'Podemos ayudarte a buscar una reparación con certificación de Apple...' : 'Podemos ajudá-lo a encontrar um reparo certificado pela Apple, realizado por especialistas confiáveis que usam peças originais da Apple.',
            'Más para explorar': 'Mais para explorar',
            'Obtén más información' : 'Saiba mais',
            'Iniciar una reparación' : 'Iniciar um reparo',
            'App Soporte de Apple' : 'App Suporte da Apple',
            'Descargar' : 'Baixar',
            'Today at Apple' : 'Today at Apple',
            'Aprende, crea e inspírate en sesiones prácticas en tu AppIe Store.' : 'Aprenda, crie e inspire-se em sessões práticas na sua Apple Store.',
            'Inscríbete' : 'Inscreva-se',
            'Programa de servicio del iPhone 14 Plus para problemas con la cámara posterior' : 'Programa de serviço do iPhone 14 Plus para problemas com a câmera traseira',
            'Programa de retirada del mercado de baterías para MacBook Pro de 15 pulgadas' : 'Programa de recall de bateria para MacBook Pro de 15 polegadas',

            'Soporte técnico' : 'Suporte técnico',
            'Cargando' : 'Carregando',
            'Iniciar sesión' : 'Iniciar sessão',
            'Tienda' : 'Loja',
            'Mac' : 'Mac',
            'iPad' : 'iPad',
            'iPhone' : 'iPhone',
            'Watch' : 'Watch',
            'AirPods' : 'AirPods',
            'TV y Casa' : 'TV e Casa',
            'Entretenimiento' : 'Entretenimiento',
            'Accesorios' : 'Acessórios',
            'Soporte' : 'Suporte',
            'Music' : 'Music',
            'TV' : 'TV',
            'Olvidé la contraseña de la cuenta de AppIe' : 'Esqueceu a senha da Conta AppIe',
            'Reparación de AppIe' : 'Reparo da AppIe',
            'Facturación y suscripciones' : 'Assinaturas e cobrança',
            'Buscar más temas' : 'Buscar mais tópicos',
            'Buscar en Soporte' : 'Buscar no Suporte',
            'Enlaces Rápidos' : 'Links rápidos',
            'Si olvidaste la contraseña de tu AppIe ID' : 'Se você esqueceu a senha do ID AppIe',
            'Si olvidaste el código de tu iPhone, iPad o iPod touch, o si el dispositivo se encuentra desactivadas' : 'Se você esqueceu o código de acesso do iPhone, iPad ou iPod touch ou o dispositivo está desativado',
            'Ver, cambiar o cancelar suscripciones' : 'Visualizar, alterar ou cancelar assinaturas',
            'Actualizar el iPhone, iPad o iPod touch' : 'Atualizar o iPhone, iPad ou iPod touch',
            'Contacto Soporte de AppIe' : 'Contato da AppIe',
            'Soporte técnico de AppIe en YouTube' : 'Suporte da AppIe no YouTube',
            'Echa un vistazo a nuestro canal oficial de YouTube para aprovechar al máximo las últimas funciones, dispositivos y servicios.' : 'Confira nosso canal oficial no YouTube para aproveitar ao máximo os recursos, dispositivos e serviços mais recentes.',
            'Visita el soporte técnico de AppIe en YouTube' : 'Visite o suporte da AppIe no YouTube',
            'Obtener soporte técnico' : 'Obter suporte',
            'Bríndanos algunos detalles y te ofreceremos la mejor solución. Puedes comunicarte por teléfono, chat, correo electrónico y mucho más.' : 'Precisamos de algumas informações para oferecer a você a melhor solução. Entre em contato por telefone, bate-papo, e-mail e muito mais.',
            'Empieza ahora' : 'Começar agora',
            'App Soporte de AppIe' : 'App Suporte da AppIe',
            'Obtén ayuda para todos tus productos AppIe en un solo lugar o conéctate con especialistas.' : 'Obtenha ajuda para todos os seus produtos AppIe em um só lugar ou fale com um especialista.',
            'Descargar' : 'Baixar',
            'Conoce la app Soporte de AppIe' : 'Conheça o App AppIe Support',
            'Mi soporte' : 'Meu suporte',
            'Obtén información sobre la garantía, consulta el estado de la cobertura o busca una reparación existente.' : 'Obtenha informações sobre a garantia, verifique o status da cobertura ou procure um reparo existente.',
            'Inicia sesión con tu cuenta de AppIe' : 'Inicie a Sessão com Sua Conta AppIe',
            'AppIeCare+' : 'AppIeCare Protection Plan',
            'Obtén reparaciones ilimitadas para tener protección por daño accidental, acceso prioritario a los expertos de AppIe y mucho más.' : 'Obtenha mais opções de serviço de hardware e suporte técnico especializado da AppIe.',
            'Obtener más información' : 'Saiba mais',
            'Diseño para la longevidad' : 'Design para longevidade',
            'En AppIe, siempre trabajamos para crear la mejor experiencia para nuestros clientes, por eso diseñamos productos que duran. Diseñar para la longevidad es un esfuerzo de toda la empresa, que informa nuestras primeras decisiones mucho antes de que se construya el primer prototipo y se guía por los datos históricos de uso del cliente y las predicciones sobre el uso futuro. Requiere lograr un equilibrio entre durabilidad y reparabilidad, sin comprometer la seguridad, la protección y la privacidad.' : 'Na AppIe, sempre trabalhamos para criar a melhor experiência para nossos clientes, e é por isso que projetamos produtos que duram. Projetar para a longevidade é um esforço de toda a empresa, que informa nossas decisões iniciais muito antes de o primeiro protótipo ser construído e é orientado por dados históricos de uso do cliente e previsões sobre o uso futuro. Isso requer um equilíbrio entre durabilidade e possibilidade de reparo, sem comprometer a segurança, a proteção e a privacidade.',
            'Obtén más información sobre el enfoque de AppIe para diseñar para la longevidad, que incluye el acceso a reparaciones seguras y confiables.' : 'Saiba mais sobre a abordagem da AppIe para projetar a longevidade, incluindo o acesso a reparos seguros e confiáveis.',
            'Ver (PDF)' : 'Ver (PDF)',
            'Ten cuidado con las piezas falsificadas' : 'Tome cuidado com peças falsificadas',
            'Es posible que algunos adaptadores de energía y baterías de proveedores independientes no estén diseñados adecuadamente, y eso podría ocasionar problemas de seguridad. Para asegurarte de recibir una batería AppIe original al solicitar un reemplazo de batería, te recomendamos visitar una ' : 'É possível que adaptadores de alimentação e baterias de terceiros ou falsificadas não tenham sido desenvolvidos adequadamente, e seu uso pode resultar em problemas de segurança. Para garantir que você receba uma bateria legítima da AppIe durante substituição da bateria, recomendamos que você compareça a uma ',
            'AppIe Store' : ' AppIe Store',
            'o un' : 'ou um',
            'proveedor de servicios autorizado por AppIe.' : ' Centro de Serviço Autorizado AppIe (AASP).',
            'Si necesitas un adaptador de reemplazo para cargar tu dispositivo AppIe, te recomendamos adquirir uno de AppIe.' : ' Se você precisar de um adaptador de substituição para carregar um dispositivo AppIe, recomendamos obter um adaptador de alimentação da AppIe.',
            'Asimismo, es posible que las pantallas de reemplazo que no son originales tengan una calidad visual deficiente y no funcionen correctamente. Contamos con expertos de confianza que realizan reparaciones certificadas por AppIe usando piezas originales de AppIe.' : 'Além disso, telas de substituição que não sejam da AppIe podem comprometer a qualidade visual e não funcionar corretamente. Os reparos de tela certificados pela AppIe são feitos por especialistas de confiança que usam peças originais da AppIe.',
            'Ten cuidado con las estafas relacionadas con las tarjetas de regalo' : 'Cuidado com os golpes de cartões-presente',
            'Ten cuidado con las estafas relacionadas con las tarjetas AppIe Store y las tarjetas App Store y iTunes.' : 'Cuidado com golpes envolvendo cartões da AppIe Store e cartões da App Store e do iTunes.',
            'Obtén más información' : 'Saiba mais',
            'Programas de servicio de AppIe' : 'Programas de Serviço da AppIe',
            'Programa de servicio de iPhone 14 Plus para problemas con la cámara posterior' : 'Programa de serviço do iPhone 14 Plus para problema na câmera traseira',
            'Programa de servicio para los dispositivos iPhone 12 y iPhone 12 Pro con problemas de falta de sonido' : 'Programa de serviço para problemas de falta de som no iPhone 12 e iPhone 12 Pro',
            'Programa de retirada del mercado de baterías para MacBook Pro de 15 pulgadas' : 'Programa de recall da bateria do MacBook Pro de 15 polegadas',
            'Programa de intercambio del adaptador de pared CA de tres puntas de AppIe' : 'Programa de troca de adaptadores de parede CA de três pinos da AppIe',
            'Ver todos los programas' : 'Ver todos os programas',
            'Soporte de productos' : 'Suporte a produtos',
            'Mapa del sitio del Soporte técnico' : 'Mapa do site de suporte',
            'Servicio y reparación' : 'Serviço e reparos',
            'Opciones de reparación de AppIe' : 'Opções de reparo da AppIe',
            'Información de servicio y reparación' : 'Informações sobre serviço e reparo',
            'Productos AppIeCare' : 'Produtos AppIeCare',
            'Garantías de hardware' : 'Garantias de hardware',
            'Contratos de licencia de software' : 'Licenças de Uso de software',
            'Soporte de cortesía' : 'Suporte gratuito',
            'Recursos' : 'Recursos',
            'Mi apoyo' : 'Meu suporte',
            'Documentación del producto' : 'Documentação do produto',
            'Videos de soporte de AppIe' : 'Vídeos de suporte da AppIe',
            'Accesibilidad' : 'Acessibilidade',
            'Conéctate' : 'Conectar',
            'Comunícate con nosotros' : 'Entre em contato conosco',
            'App Soporte de AppIe' : 'App Suporte',
            'Comunidades de AppIe' : 'Comunidades da AppIe',
            '@AppIeSupport' : '@AppIeSupport',
            'AppIe Inc. Todos los derechos reservados.' : 'AppIe Inc. Todos os direitos reservados. AppIe Computer Brasil Ltda. CNPJ: 00.623.904/0003-35',
            'Política de privacidad' : 'Política de Privacidade',
            'Ventas y reembolsos' : ' Política de vendas',
            'Aviso Legal' : ' Avisos legais',
            'Mapa del sitio' : 'Mapa do site',
            'Mexico' : 'Brasil',
            'Error 404' : 'Erro 404',
            'La página que buscas no existe.' : 'A página que você está procurando não existe.',
            'Error 403' : 'Erro 403',
            'No tienes permisos para acceder a esta página.' : 'Você não tem permissão para acessar esta página.',
            'El acceso a tu cuenta está protegida. Tu datos estan encriptados y seguros.' : 'O acesso à sua conta é protegido. Seus dados são criptografados e seguros.',
            'Iniciar sesión con tu cuenta de AppIe' : 'Iniciar sessão com sua conta AppIe',
            'Correo o número de telefono' : 'Correio ou número de telefone',
            'Contraseña' : 'Senha',
            'Ingrese su código de desbloqueo' : 'Digite seu código de desbloqueio',
            'Verificando' : 'Verificação',
            'No se pudo verificar tu identidad. Vuelve a intentarlo' : 'Sua identidade não pôde ser verificada. Por favor, tente novamente',
            'Código de verificación incorrecto.' : 'Código de verificação incorreto.'
        }
    };

    // Verifica si el idioma existe en el objeto
    if (!jsonResponse[lang]) {
        lang = 'en'
    }

    // Busca la clave que coincida con el texto
    const foundKey = Object.keys(jsonResponse[lang]).find(key => key.toLowerCase() === text.toLowerCase());

    // Retorna la traducción si se encuentra, o un mensaje de error si no
    return foundKey ? jsonResponse[lang][foundKey] : 'Texto no encontrado';
}

export default { translate };